pipeline {
    agent any
 stages {
        stage('Checkout') {
            steps {
               
                   echo 'New Branch'
            }
        }
    
    
        stage('Build') {
            steps {
              
               echo 'Building the code'
            }
        }
        
        stage('Test Build') {
            steps {
              
               echo 'Building the code'
            }
        }
         stage('QA Deployement') {
            steps {
              
               echo 'Deploy the code'
            }
        }
           stage('Production Deployement') {
            steps {
              
               echo 'Prod Code'
            }
        }
    }
}
